// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using challenge_api_dotnet.Data;

#nullable disable

namespace challenge_api_dotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240515000000_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM556934")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("challenge_api_dotnet.Models.MarcadorArucoMovel", b =>
                {
                    b.Property<int>("IdMarcadorMovel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MARCADOR_MOVEL")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_MARCADOR_M_CH\".NEXTVAL");

                    b.Property<string>("CodigoAruco")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CODIGO_ARUCO");

                    b.Property<DateTime?>("DataInstalacao")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_INSTALACAO");

                    b.Property<int?>("MotoIdMoto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOTO_ID_MOTO");

                    b.HasKey("IdMarcadorMovel");

                    b.HasIndex("MotoIdMoto");

                    b.ToTable("MARCADOR_ARUCO_MOVEL", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MarcadorFixo", b =>
                {
                    b.Property<int>("IdMarcadorArucoFixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MARCADOR_ARUCO_FIXO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_MARCADOR_F_CH\".NEXTVAL");

                    b.Property<string>("CodigoAruco")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CODIGO_ARUCO");

                    b.Property<int?>("PatioIdPatio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIO_ID_PATIO");

                    b.Property<decimal?>("XPos")
                        .HasColumnType("FLOAT(10)")
                        .HasColumnName("X_POS");

                    b.Property<decimal?>("YPos")
                        .HasColumnType("FLOAT(10)")
                        .HasColumnName("Y_POS");

                    b.HasKey("IdMarcadorArucoFixo");

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("MARCADOR_FIXO", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MedicaoPosicao", b =>
                {
                    b.Property<int>("IdMedicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MEDICAO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_MEDICAO_CH\".NEXTVAL");

                    b.Property<decimal?>("DistanciaM")
                        .HasColumnType("FLOAT(10)")
                        .HasColumnName("DISTANCIA_M");

                    b.Property<int?>("MarcadorFixoIdMarcadorArucoFixo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MARCADOR_FIXO_ID_MARCADOR_ARUCO_FIXO");

                    b.Property<int?>("PosicaoIdPosicao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POSICAO_ID_POSICAO");

                    b.HasKey("IdMedicao");

                    b.HasIndex("MarcadorFixoIdMarcadorArucoFixo");

                    b.HasIndex("PosicaoIdPosicao");

                    b.ToTable("MEDICAO_POSICAO", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_MOTO_CH\".NEXTVAL");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(7)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Status")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(65)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdMoto");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasFilter((string)null);

                    b.ToTable("MOTO", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Patio", b =>
                {
                    b.Property<int>("IdPatio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_PATIO_CH\".NEXTVAL");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("IdPatio");

                    b.ToTable("PATIO", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Posicao", b =>
                {
                    b.Property<int>("IdPosicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_POSICAO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_POS_CH\".NEXTVAL");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_HORA");

                    b.Property<int?>("MotoIdMoto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOTO_ID_MOTO");

                    b.Property<int?>("PatioIdPatio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIO_ID_PATIO");

                    b.Property<decimal?>("XPos")
                        .HasColumnType("FLOAT(10)")
                        .HasColumnName("X_POS");

                    b.Property<decimal?>("YPos")
                        .HasColumnType("FLOAT(10)")
                        .HasColumnName("Y_POS");

                    b.HasKey("IdPosicao");

                    b.HasIndex("MotoIdMoto");

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("POSICAO", "RM556934");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_USUARIO_CH\".NEXTVAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("PatioIdPatio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIO_ID_PATIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ativo'");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("USUARIO", "RM556934", tb =>
                        {
                            tb.HasCheckConstraint("USUARIO_TIPO_CHK", "\"TIPO\" IN (''USER'',''ADMIN'')");
                        });
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MarcadorArucoMovel", b =>
                {
                    b.HasOne("challenge_api_dotnet.Models.Moto", "MotoIdMotoNavigation")
                        .WithMany("MarcadoresArucoMoveis")
                        .HasForeignKey("MotoIdMoto")
                        .HasConstraintName("SYS_C004862169");

                    b.Navigation("MotoIdMotoNavigation");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MarcadorFixo", b =>
                {
                    b.HasOne("challenge_api_dotnet.Models.Patio", "PatioIdPatioNavigation")
                        .WithMany("MarcadoresFixos")
                        .HasForeignKey("PatioIdPatio")
                        .HasConstraintName("SYS_C004862167");

                    b.Navigation("PatioIdPatioNavigation");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MedicaoPosicao", b =>
                {
                    b.HasOne("challenge_api_dotnet.Models.MarcadorFixo", "MarcadorFixoIdMarcadorArucoFixoNavigation")
                        .WithMany("MedicoesPosicoes")
                        .HasForeignKey("MarcadorFixoIdMarcadorArucoFixo")
                        .HasConstraintName("SYS_C004862172");

                    b.HasOne("challenge_api_dotnet.Models.Posicao", "PosicaoIdPosicaoNavigation")
                        .WithMany("MedicoesPosicoes")
                        .HasForeignKey("PosicaoIdPosicao")
                        .HasConstraintName("SYS_C004862171");

                    b.Navigation("MarcadorFixoIdMarcadorArucoFixoNavigation");

                    b.Navigation("PosicaoIdPosicaoNavigation");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Posicao", b =>
                {
                    b.HasOne("challenge_api_dotnet.Models.Moto", "MotoIdMotoNavigation")
                        .WithMany("Posicoes")
                        .HasForeignKey("MotoIdMoto")
                        .HasConstraintName("SYS_C004862164");

                    b.HasOne("challenge_api_dotnet.Models.Patio", "PatioIdPatioNavigation")
                        .WithMany("Posicoes")
                        .HasForeignKey("PatioIdPatio")
                        .HasConstraintName("SYS_C004862165");

                    b.Navigation("MotoIdMotoNavigation");

                    b.Navigation("PatioIdPatioNavigation");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Usuario", b =>
                {
                    b.HasOne("challenge_api_dotnet.Models.Patio", "PatioIdPatioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("PatioIdPatio")
                        .IsRequired()
                        .HasConstraintName("USUARIO_PATIO_FK");

                    b.Navigation("PatioIdPatioNavigation");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.MarcadorFixo", b =>
                {
                    b.Navigation("MedicoesPosicoes");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Moto", b =>
                {
                    b.Navigation("MarcadoresArucoMoveis");

                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Patio", b =>
                {
                    b.Navigation("MarcadoresFixos");

                    b.Navigation("Posicoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("challenge_api_dotnet.Models.Posicao", b =>
                {
                    b.Navigation("MedicoesPosicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
